name: Run Build Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build tools
        run: python -m pip install build wheel
      - name: Build distribution packages
        run: python -m build
      - name: Install repo
        run: pip install .

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -e ".[dev]" pytest pytest-cov
      - name: Run unit tests
        run: pytest test/ -v --cov=ovos_utterance_plugin_cancel --cov-report=term-missing
